### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by avosirenfal** [merfed/Coffee#2]
Abusing the issue tracker because it's a convenient way to contact you.

Talk about a nostalgia trip. I was active in the WoW emulation scene many years ago. So strange seeing your name and some of these tools again.

Your stuff on MMOwned let me do some cool things a long time ago. I never got a chance to thank you, so... thanks :)

What kinda stuff do you do now, if you don't mind me asking? I always wondered where people would end up professionally, but especially you since you had a pretty varied skillset. Can't say I ever thought I might found out though.

**Comment by merfed** [comment]
Hey!

No problem, glad you enjoyed doing a lot of the cool things you could do with these tools way back when. It's disappointing the community pretty much all disappeared over the years, but I guess we got our own lives. ;)

I ended up going to school for animation, and now I do layouts and storyboards for various things.

**Comment by avosirenfal** [comment]
Do you have any IM accounts now? I think MSN died along with the community at some point :P
